import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { formatDate, formatLabel } from '../../lib/format';
import { useVisits } from './api/useVisits';
import type { VisitRow } from './api/useVisits';
import VisitDetail from './Visitdetail';
import { canonicalOutreachOutcome, downloadVisitCsv, outcomeCodeLabel, outreachOutcomeLabel, OUTREACH_OUTCOMES, OUTREACH_TYPES, participantNames, reportedOutreachType } from './reporting';
import '../../styles/outreachVisits.css';

const value = (params: URLSearchParams, name: string) => params.get(name) ?? '';
export default function OutreachVisits() {
  const { data: visits = [], isLoading, error } = useVisits();
  const [params, setParams] = useSearchParams(); const [selected, setSelected] = useState<VisitRow | null>(null);
  const search = value(params, 'search'); const type = value(params, 'type'); const outcome = value(params, 'status'); const staff = value(params, 'staff'); const from = value(params, 'from'); const to = value(params, 'to');
  const setFilter = (name: string, next: string) => setParams((current) => { const updated = new URLSearchParams(current); if (next) updated.set(name, next); else updated.delete(name); return updated; }, { replace: true });
  const reportable = useMemo(() => visits.filter((visit) => reportedOutreachType(visit.outreach_type, visit.outreach_happened, visit.did_instead)), [visits]);
  const staffOptions = useMemo(() => [...new Map(reportable.filter((visit) => visit.data_capturer_id).map((visit) => [visit.data_capturer_id!, visit.data_capturer?.name || 'Unknown staff'])).entries()].sort((a,b) => a[1].localeCompare(b[1])), [reportable]);
  const filtered = useMemo(() => reportable.filter((visit) => {
    const query = search.trim().toLowerCase(); const names = participantNames(visit).join(' ').toLowerCase();
    return (!query || names.includes(query) || visit.practitioner?.ecdc?.name?.toLowerCase().includes(query) || visit.comments?.toLowerCase().includes(query))
      && (!type || reportedOutreachType(visit.outreach_type, visit.outreach_happened, visit.did_instead) === type) && (!outcome || canonicalOutreachOutcome(visit.outreach_happened, visit.did_instead) === outcome)
      && (!staff || visit.data_capturer_id === staff) && (!from || Boolean(visit.date && visit.date >= from)) && (!to || Boolean(visit.date && visit.date <= to));
  }), [reportable, search, type, outcome, staff, from, to]);
  const totals = useMemo(() => ({ parents: filtered.reduce((sum, visit) => sum + Number(visit.parents_attending ?? visit.parents_trained ?? 0), 0), books: filtered.reduce((sum, visit) => sum + Number(visit.books_distributed_to_children ?? visit.children_books ?? 0), 0), km: filtered.reduce((sum, visit) => sum + Number(visit.transport_km ?? 0), 0), cost: filtered.reduce((sum, visit) => sum + Number(visit.transport_cost ?? 0), 0) }), [filtered]);

  return <div className="page ov-report-page"><main className="ov-report-main">
    <header className="ov-report-title"><div><h1>Outreach Visits</h1><p>Canonical programme reporting, including ECDC Mapping visits; ECDC-update submissions are excluded.</p></div><button className="lyt-btn ov-report-primary" disabled={!filtered.length} onClick={() => downloadVisitCsv(filtered)}>Export CSV</button></header>
    <section className="ov-report-filters" aria-label="Visit filters"><input aria-label="Search visits" placeholder="Search practitioner, ECDC or notes" value={search} onChange={(event) => setFilter('search', event.target.value)} /><select aria-label="Outreach type" value={type} onChange={(event) => setFilter('type', event.target.value)}><option value="">All types</option>{OUTREACH_TYPES.map((item) => <option key={item} value={item}>{formatLabel(item)}</option>)}</select><select aria-label="Outcome" value={outcome} onChange={(event) => setFilter('status', event.target.value)}><option value="">All outcomes</option>{OUTREACH_OUTCOMES.map((item) => <option key={item} value={item}>{outcomeCodeLabel(item)}</option>)}</select><select aria-label="Staff" value={staff} onChange={(event) => setFilter('staff', event.target.value)}><option value="">All staff</option>{staffOptions.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select><input aria-label="From date" type="date" value={from} onChange={(event) => setFilter('from', event.target.value)} /><input aria-label="To date" type="date" value={to} onChange={(event) => setFilter('to', event.target.value)} /><button className="lyt-btn" onClick={() => setParams({})}>Clear</button></section>
    <section className="ov-report-stats"><div><strong>{filtered.length}</strong><span>Visits</span></div><div><strong>{totals.parents}</strong><span>Parents attending</span></div><div><strong>{totals.books}</strong><span>Books distributed</span></div><div><strong>{Math.round(totals.km)} km</strong><span>Distance</span></div><div><strong>R{Math.round(totals.cost).toLocaleString()}</strong><span>Transport cost</span></div></section>
    {isLoading ? <div className="ov-report-state">Loading visits…</div> : error ? <div className="ov-report-state" role="alert">Outreach visits could not be loaded. {error.message}</div> : !filtered.length ? <div className="ov-report-state">No results match the filters.</div> : <div className="ov-report-table-wrap"><table className="ov-report-table"><thead><tr><th>Date</th><th>Practitioner(s)</th><th>ECDC / area</th><th>Staff</th><th>Type / outcome</th><th>Parents</th><th>Books</th><th>Transport</th><th>Notes</th></tr></thead><tbody>{filtered.map((visit) => <tr key={visit.id} tabIndex={0} onClick={() => setSelected(visit)} onKeyDown={(event) => { if (event.key === 'Enter') setSelected(visit); }}><td data-label="Date">{formatDate(visit.date)}</td><td data-label="Practitioner(s)"><strong>{participantNames(visit).join(', ') || 'Unlinked'}</strong>{participantNames(visit).length > 1 && <small>{participantNames(visit).length} practitioners</small>}</td><td data-label="ECDC / area">{visit.practitioner?.ecdc?.name || '—'}<small>{visit.practitioner?.ecdc?.area || ''}</small></td><td data-label="Staff">{visit.data_capturer?.name || '—'}</td><td data-label="Type / outcome">{formatLabel(reportedOutreachType(visit.outreach_type, visit.outreach_happened, visit.did_instead))}<small>{outreachOutcomeLabel(visit.outreach_happened, visit.did_instead)}</small></td><td data-label="Parents">{visit.parents_attending ?? visit.parents_trained ?? '—'}<small>{visit.attendance_rate_percent == null ? '' : `${visit.attendance_rate_percent}% attendance`}</small></td><td data-label="Books">{visit.books_distributed_to_children ?? visit.children_books ?? '—'}<small>{visit.books_left_with_practitioner ?? visit.books_to_practitioner ?? 0} left</small></td><td data-label="Transport">{formatLabel(visit.transport_type)}<small>{visit.transport_km || 0} km · R{Number(visit.transport_cost || 0).toLocaleString()}</small></td><td data-label="Notes" className="ov-report-notes">{visit.comments || '—'}</td></tr>)}</tbody></table></div>}
  </main>{selected && <aside className="ov-detail-panel ov-detail-panel--open"><VisitDetail visit={selected} onClose={() => setSelected(null)} /></aside>}</div>;
}
